package com.edifabric.nativex12;

/** Library-level status codes. Validation codes come from the engine. */
public enum ErrorCode {
    SUCCESS(0),
    INSUFFICIENT_CAPACITY(1),
    UNKNOWN(501),
    NO_CONNECTION(502),
    MODEL_MAP_INVALID(503),
    INCORRECT_INPUT(611),
    LOGGER_INITIALIZATION(612),
    MAP_DESERIALIZATION(613),
    INCORRECT_CAPACITY(614),
    MAP_NOT_SET(615),
    INCORRECT_MODE(616),
    NO_JSON(617),
    VALIDATION_UNAVAILABLE(618),
    VALIDATION_SERIALIZATION(619),
    INCORRECT_TOKEN(620),
    CONFIG_DESERIALIZATION(621),
    SPLIT_SEGMENT_ID_MISSING(622),
    SPLIT_NOT_STARTED(623),
    NO_RESULT(624),
    RESULT_SIZE_MISMATCH(625),
    MERGE_NOT_STARTED(626),
    INCORRECT_OUTPUT_POINTER(627),
    INCORRECT_SERIAL(628),
    LICENSE_NOT_INSTALLED(629),
    APP_VERSION_EXCEEDED(630),
    TOKEN_EXPIRED(631),
    TOKEN_MISSING(632),
    MAX_LICENSES_EXCEEDED(633),
    LICENSE_SNAPSHOT_MISSING(634),
    LICENSE_NOT_SET(635),
    RATE_EXCEEDED(636),
    INVALID_JSON(637),
    INCORRECT_LICENSE(638),
    LICENSE_QUOTA_EXCEEDED(639);

    private final int value;

    ErrorCode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
